# Generated by Django 2.2.4 on 2022-03-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='product_image',
        ),
    ]
