# Generated by Django 2.2.4 on 2022-03-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_address_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='promotions',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Product_Type',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
