# Generated by Django 2.2.4 on 2022-03-20 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birth_date',
        ),
    ]
